# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0002_auto_20160614_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistrack',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='analysistrack',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date modified'),
        ),
        migrations.AddField(
            model_name='analysistrack',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='analysistrack',
            name='title',
            field=models.CharField(blank=True, max_length=512, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='analysistrack',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='subprocessor',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
    ]
