# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0002_auto_20190618_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocessor',
            name='sub_processor_id',
            field=models.CharField(max_length=128, verbose_name='sub_processor_id'),
        ),
    ]
