# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-04 14:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0004_result_run_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-date_added'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
    ]
