# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeside_server', '0004_auto_20160616_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uuid', models.CharField(blank=True, max_length=255, unique=True, verbose_name='uuid')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='timeside_server.Preset', verbose_name='preset')),
                ('sub_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='timeside_server.SubProcessor', verbose_name='sub_processor')),
            ],
            options={
                'db_table': 'timeside_analysis',
                'verbose_name': 'Analysis',
            },
        ),
        migrations.RemoveField(
            model_name='analysistrack',
            name='author',
        ),
        migrations.RemoveField(
            model_name='analysistrack',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='analysistrack',
            name='sub_processor',
        ),
        migrations.DeleteModel(
            name='AnalysisTrack',
        ),
    ]
