# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0004_result_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='run_time',
            field=models.FloatField(blank=True, default=float("nan"), null=True, verbose_name='Run time'),
        ),
    ]
