# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0005_auto_20191104_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='source_access',
            field=models.BooleanField(default=False),
        ),
    ]
