# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0006_provider_source_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtrack',
            name='start_time',
            field=models.FloatField(default=0, verbose_name='start time (s)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hdf5',
            field=models.FileField(blank=True, max_length=1024, upload_to='results/%Y/%m/%d', verbose_name='HDF5 result file'),
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeside_server.Provider', verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source_file',
            field=models.FileField(blank=True, max_length=1024, upload_to='items/%Y/%m/%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='parameters',
            field=models.TextField(blank=True, default='{}', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='timeside_server.Processor', verbose_name='processor'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(blank=True, max_length=1024, upload_to='results/%Y/%m/%d', verbose_name='Output file'),
        ),
        migrations.AlterField(
            model_name='result',
            name='hdf5',
            field=models.FileField(blank=True, max_length=1024, upload_to='results/%Y/%m/%d', verbose_name='HDF5 result file'),
        ),
        migrations.AlterField(
            model_name='subprocessor',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_results', to='timeside_server.Processor', verbose_name='processor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='timeside_server.Experience', verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='timeside_server.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='task',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='timeside_server.Selection', verbose_name='selection'),
        ),
    ]
