# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0007_auto_20160705_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='pid',
            field=models.CharField(choices=[(b'Analyzers', [(b'vamp_simple_host', b'vamp_simple_host'), (b'aubio_melenergy', b'aubio_melenergy'), (b'aubio_mfcc', b'aubio_mfcc'), (b'aubio_pitch', b'aubio_pitch'), (b'aubio_specdesc', b'aubio_specdesc'), (b'aubio_temporal', b'aubio_temporal'), (b'yaafe', b'yaafe'), (b'spectrogram_analyzer', b'spectrogram_analyzer'), (b'onset_detection_function', b'onset_detection_function'), (b'spectrogram_analyzer_buffer', b'spectrogram_analyzer_buffer'), (b'waveform_analyzer', b'waveform_analyzer'), (b'irit_singing_turns', b'irit_singing_turns'), (b'irit_diverg', b'irit_diverg'), (b'irit_diverg2', b'irit_diverg2'), (b'irit_harmo_tracking', b'irit_harmo_tracking'), (b'irit_harmo_cluster', b'irit_harmo_cluster'), (b'irit_monopoly', b'irit_monopoly'), (b'irit_music_sln', b'irit_music_sln'), (b'irit_music_snb', b'irit_music_snb'), (b'irit_startseg', b'irit_startseg'), (b'irit_singing', b'irit_singing'), (b'irit_speech_4hz', b'irit_speech_4hz'), (b'irit_speech_entropy', b'irit_speech_entropy'), (b'irit_tempogram', b'irit_tempogram'), (b'labri_singing', b'labri_singing'), (b'labri_speech_music_noise', b'labri_speech_music_noise'), (b'limsi_sad', b'limsi_sad'), (b'limsi_diarization', b'limsi_diarization'), (b'mean_dc_shift', b'mean_dc_shift'), (b'level', b'level')]), (b'Graphers', [(b'grapher_aubio_pitch', b'grapher_aubio_pitch'), (b'grapher_onset_detection_function', b'grapher_onset_detection_function'), (b'grapher_waveform', b'grapher_waveform'), (b'spectrogram_log', b'spectrogram_log'), (b'spectrogram_lin', b'spectrogram_lin'), (b'waveform_simple', b'waveform_simple'), (b'waveform_centroid', b'waveform_centroid'), (b'waveform_contour_black', b'waveform_contour_black'), (b'waveform_contour_white', b'waveform_contour_white'), (b'waveform_transparent', b'waveform_transparent'), (b'grapher_irit_singingturns', b'grapher_irit_singingturns'), (b'grapher_irit_monopoly_segments', b'grapher_irit_monopoly_segments'), (b'grapher_irit_music_sln_segments', b'grapher_irit_music_sln_segments'), (b'grapher_irit_music_snb_segments', b'grapher_irit_music_snb_segments'), (b'grapher_irit_startseg', b'grapher_irit_startseg'), (b'grapher_irit_singing_segments', b'grapher_irit_singing_segments'), (b'grapher_irit_speech_4hz_segments', b'grapher_irit_speech_4hz_segments'), (b'grapher_irit_speech_4hz_segments_median', b'grapher_irit_speech_4hz_segments_median'), (b'grapher_irit_speech_entropy_segments', b'grapher_irit_speech_entropy_segments'), (b'grapher_irit_tempogram', b'grapher_irit_tempogram'), (b'grapher_labri_singing', b'grapher_labri_singing'), (b'grapher_labri_smn_speech', b'grapher_labri_smn_speech'), (b'grapher_labri_smn_music', b'grapher_labri_smn_music'), (b'grapher_limsi_sad_etape', b'grapher_limsi_sad_etape'), (b'grapher_limsi_sad_maya', b'grapher_limsi_sad_maya'), (b'grapher_limsi_sad_adaptive', b'grapher_limsi_sad_adaptive'), (b'grapher_limsi_diarization_speakers', b'grapher_limsi_diarization_speakers'), (b'grapher_limsi_diarization_speakers_maya', b'grapher_limsi_diarization_speakers_maya')]), (b'Encoders', [(b'live_encoder', b'live_encoder'), (b'flac_encoder', b'flac_encoder'), (b'aac_encoder', b'aac_encoder'), (b'mp3_encoder', b'mp3_encoder'), (b'vorbis_encoder', b'vorbis_encoder'), (b'opus_encoder', b'opus_encoder'), (b'wav_encoder', b'wav_encoder'), (b'webm_encoder', b'webm_encoder')])], max_length=128, unique=True, verbose_name='pid'),
        ),
    ]
