# Generated by Django 2.2 on 2020-05-26 15:02

from django.db import migrations
from django.core.management import call_command


def update_providers(apps, schema_editor):
    # Clean deprecated deezer provider, delete provider duplicates
    # update provider's fields and ensure item's provider FK
    call_command('timeside-provider-deezer-preview', verbosity=0)

def save_items(apps, schema_editor):
    # Clean deprecated deezer provider, delete provider duplicates
    # update provider's fields and ensure item's provider FK
    call_command('timeside-save-items', verbosity=0)

class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0009_item_samplerate'),
    ]

    operations = [
        # migrations.RunPython(save_items),
        # migrations.RunPython(update_providers)
    ]
