# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0009_auto_20160926_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='timeside_server.AnnotationTrack', verbose_name='annotation'),
        ),
    ]
