# Generated by Django 2.2 on 2020-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0010_populate_samplerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='render_type',
            field=models.IntegerField(choices=[(0, 'vector'), (1, 'image')], default=0, help_text='Rendering types:\n\nvector: 0\n\nimage: 1', verbose_name='render type'),
        ),
    ]
