# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0010_auto_20160928_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='pid',
            field=models.CharField(choices=[(b'Analyzers', [(b'vamp_simple_host', b'vamp_simple_host'), (b'aubio_melenergy', b'aubio_melenergy'), (b'aubio_mfcc', b'aubio_mfcc'), (b'aubio_pitch', b'aubio_pitch'), (b'aubio_specdesc', b'aubio_specdesc'), (b'aubio_temporal', b'aubio_temporal'), (b'yaafe', b'yaafe'), (b'spectrogram_analyzer', b'spectrogram_analyzer'), (b'onset_detection_function', b'onset_detection_function'), (b'spectrogram_analyzer_buffer', b'spectrogram_analyzer_buffer'), (b'waveform_analyzer', b'waveform_analyzer'), (b'mean_dc_shift', b'mean_dc_shift'), (b'level', b'level')]), (b'Graphers', [(b'grapher_aubio_pitch', b'grapher_aubio_pitch'), (b'grapher_onset_detection_function', b'grapher_onset_detection_function'), (b'grapher_waveform', b'grapher_waveform'), (b'spectrogram_log', b'spectrogram_log'), (b'spectrogram_lin', b'spectrogram_lin'), (b'waveform_simple', b'waveform_simple'), (b'waveform_centroid', b'waveform_centroid'), (b'waveform_contour_black', b'waveform_contour_black'), (b'waveform_contour_white', b'waveform_contour_white'), (b'waveform_transparent', b'waveform_transparent')]), (b'Encoders', [(b'live_encoder', b'live_encoder'), (b'flac_encoder', b'flac_encoder'), (b'aac_encoder', b'aac_encoder'), (b'mp3_encoder', b'mp3_encoder'), (b'vorbis_encoder', b'vorbis_encoder'), (b'opus_encoder', b'opus_encoder'), (b'wav_encoder', b'wav_encoder'), (b'webm_encoder', b'webm_encoder')])], max_length=128, unique=True, verbose_name='pid'),
        ),
    ]
