# Generated by Django 2.2.20 on 2021-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0011_analysis_render_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_modified'], 'verbose_name': 'item'},
        ),
        migrations.AddField(
            model_name='analysis',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'failed'), (1, 'draft'), (2, 'pending'), (3, 'running'), (4, 'done')], default=2, help_text="Task's status:\n\nfailed: 0\n\ndraft: 1\n\npending: 2\n\nrunning: 3\n\ndone: 4", verbose_name='status'),
        ),
    ]
