# Generated by Django 2.2.20 on 2021-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0011_analysis_render_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_modified'], 'verbose_name': 'item'},
        ),
        migrations.AddField(
            model_name='task',
            name='test_bool',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to evoid celery when testing'),
        ),
    ]
