# Generated by Django 2.2.20 on 2021-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0012_auto_20210616_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
    ]
