# Generated by Django 2.2.20 on 2021-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0012_auto_20210504_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test_bool',
        ),
        migrations.AddField(
            model_name='analysis',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
    ]
