# Generated by Django 2.2.20 on 2021-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0012_auto_20210504_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test_bool',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to evoid celery when testing'),
        ),
    ]
