# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 21:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0013_auto_20161024_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='parameters_schema',
            field=jsonfield.fields.JSONField(default={b'$schema': b'http://json-schema.org/schema#', b'properties': {}, b'type': b'object'}),
        ),
    ]
