# Generated by Django 2.2.20 on 2021-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0013_item_test_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test_bool',
        ),
        migrations.AddField(
            model_name='item',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_bool',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
    ]
