# Generated by Django 2.2.20 on 2021-05-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0014_auto_20210504_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='test_bool',
        ),
    ]
