# Generated by Django 2.2.20 on 2021-05-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0015_auto_20210504_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test_bool',
        ),
    ]
