# Generated by Django 2.2.24 on 2022-02-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0015_annotation_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='analysistrack',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Analysis Track'},
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Annotation'},
        ),
        migrations.AlterModelOptions(
            name='annotationtrack',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Annotation Track'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['-date_modified'], 'verbose_name': 'selection'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
