# Generated by Django 2.2.20 on 2021-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0016_remove_item_test_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test_bool',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
    ]
