# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-14 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0016_item_audio_duration'),
        ('timeside_server', '0016_auto_20181024_1442'),
    ]

    operations = [
    ]
