# Generated by Django 2.2.20 on 2021-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0017_item_test_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test_bool',
        ),
    ]
