# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_uri',
            field=models.CharField(blank=True, max_length=1024, verbose_name='external_uri'),
        ),
    ]
