# Generated by Django 2.2.24 on 2022-12-22 16:14

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0018_auto_20220414_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_file',
            field=models.FileField(blank=True, help_text='Audio file to process.', max_length=1024, storage=django_minio_backend.models.MinioBackend(bucket_name='timeside-upload'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='file'),
        ),
    ]
