# Generated by Django 2.2.24 on 2023-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0018_auto_20220414_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='domain',
            field=models.CharField(blank=True, max_length=1024, verbose_name='domain'),
        ),
    ]
