# Generated by Django 2.2.20 on 2021-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0018_remove_item_test_bool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='test_bool',
            new_name='test',
        ),
        migrations.AddField(
            model_name='analysis',
            name='test',
            field=models.BooleanField(blank=True, default=False, help_text='boolean to avoid celery when testing'),
        ),
    ]
