# Generated by Django 2.2.24 on 2023-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0019_provider_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='name'),
        ),
    ]
