# Generated by Django 2.2.24 on 2023-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0020_auto_20230207_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='album',
            field=models.CharField(blank=True, max_length=256, verbose_name='album'),
        ),
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(blank=True, max_length=256, verbose_name='artist'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='picture URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duration of the audio source', null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='item',
            name='external_id',
            field=models.CharField(blank=True, help_text="Provider's id of the audio source.\n\ne.g. for Deezer preview: 4763165\n\ne.g. for YouTube: oRdxUFDoQe0", max_length=256, verbose_name='external ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='external_uri',
            field=models.CharField(blank=True, help_text="Provider's URI of the audio source.\n\ne.g. for Deezer preview: http://www.deezer.com/track/4763165\n\ne.g. for YouTube: https://www.youtube.com/watch?v=oRdxUFDoQe0", max_length=1024, verbose_name='external URI'),
        ),
        migrations.AlterField(
            model_name='item',
            name='samplerate',
            field=models.IntegerField(blank=True, help_text='Sampling rate of audio source', null=True, verbose_name='sampling rate'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source_file',
            field=models.FileField(blank=True, help_text='Audio source file to process', max_length=1024, upload_to='items/%Y/%m/%d', verbose_name='source file'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source_url',
            field=models.URLField(blank=True, help_text='Audio source streamable URL to process', max_length=1024, verbose_name='source URL'),
        ),
    ]
