# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0020_task_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideridentifier',
            name='url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='URL'),
        ),
    ]
