# Generated by Django 3.2.18 on 2023-04-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0021_auto_20230308_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-date_modified'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='hdf5',
        ),
    ]
