# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-19 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0021_provideridentifier_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideridentifier',
            name='url',
        ),
    ]
