# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0022_remove_provideridentifier_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideridentifier',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='item',
            name='provider_identifier',
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeside_server.Provider', verbose_name='provider'),
        ),
        migrations.DeleteModel(
            name='ProviderIdentifier',
        ),
    ]
