# Generated by Django 3.2.18 on 2023-04-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0022_auto_20230419_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistrack',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tracks', to='timeside_server.item', verbose_name='item'),
        ),
    ]
