# Generated by Django 3.2.18 on 2023-04-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0023_alter_analysistrack_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='parameters',
            field=models.JSONField(blank=True, default='{}', verbose_name='Parameters'),
        ),
    ]
