# Generated by Django 3.2.18 on 2023-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0024_alter_preset_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parameters'),
        ),
    ]
