# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0024_provider_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='url',
        ),
    ]
