# Generated by Django 3.2.18 on 2023-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0025_alter_preset_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='parameters_schema',
            field=models.JSONField(default=dict),
        ),
    ]
