# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-10 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0025_remove_provider_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='external_id',
        ),
    ]
