# Generated by Django 3.2.18 on 2023-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0026_auto_20230427_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'failed'), (1, 'draft'), (2, 'pending'), (3, 'running'), (4, 'done')], default=2, help_text="Task's status:\n\nfailed: 0\n\ndraft: 1\n\npending: 2\n\nrunning: 3\n\ndone: 4", null=True, verbose_name='status'),
        ),
    ]
