# Generated by Django 3.2.18 on 2023-05-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0027_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-date_modified', 'title'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['-date_modified', 'processor__pid'], 'verbose_name': 'Preset', 'verbose_name_plural': 'Presets'},
        ),
    ]
