# Generated by Django 3.2.18 on 2023-05-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0028_auto_20230510_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='test',
        ),
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
        migrations.AddField(
            model_name='analysis',
            name='synchronous',
            field=models.BooleanField(default=False, help_text='executed in main thread synchronously'),
        ),
        migrations.AddField(
            model_name='task',
            name='synchronous',
            field=models.BooleanField(default=False, help_text='executed in main thread synchronously'),
        ),
        migrations.AlterField(
            model_name='item',
            name='test',
            field=models.BooleanField(default=False, help_text='testing purpose'),
        ),
    ]
