# Generated by Django 3.2.18 on 2023-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0029_auto_20230515_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='synchronous',
            field=models.BooleanField(default=False, help_text='executed in main thread synchronously'),
        ),
    ]
