# Generated by Django 3.2.18 on 2023-05-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeside_server', '0030_processor_synchronous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='synchronous',
        ),
        migrations.RemoveField(
            model_name='task',
            name='synchronous',
        ),
    ]
